// const fetch = require('node-fetch');

// const RMapi = () => {
//   const RickandMorty = fetch("https://rickandmortyapi.com/api/character/?page=19")
//     .then((response) => {
//   return response.json();
//   })
//     .then((data) => {
//   console.log(data);
//   })
// }

// RMapi()

const chars = [
  {
    id: 1,
    name: 'Rick Sanchez', status: 'Alive', species: 'Human', type: '', gender: 'Male' },
  {
    id: 2,
    name: 'Morty Smith',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Male',
  },
  {
    id: 3,
    name: 'Summer Smith',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Female',
  },
  {
    id: 4,
    name: 'Beth Smith',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Female',
  },
  {
    id: 5,
    name: 'Jerry Smith',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Male',
  },
  {
    id: 6,
    name: 'Abadango Cluster Princess',
    status: 'Alive',
    species: 'Alien',
    type: '',
    gender: 'Female',
  },
  {
    id: 7,
    name: 'Abradolf Lincler',
    status: 'unknown',
    species: 'Human',
    type: 'Genetic experiment',
    gender: 'Male',
  }
]







//   {
//     id: 8,
//     name: 'Adjudicator Rick',
//     status: 'Dead',
//     species: 'Human',
//     type: '',
//     gender: 'Male',
//   },
//   {
//     id: 9,
//     name: 'Agency Director',
//     status: 'Dead',
//     species: 'Human',
//     type: '',
//     gender: 'Male',
//   },
//   {
//     id: 10,
//     name: 'Alan Rails',
//     status: 'Dead',
//     species: 'Human',
//     type: 'Superhuman (Ghost trains summoner)',
//     gender: 'Male',
//   },
//   {
//     id: 11,
//     name: 'Albert Einstein',
//     status: 'Dead',
//     species: 'Human',
//     type: '',
//     gender: 'Male',
//   },
//   {
//     id: 12,
//     name: 'Alexander',
//     status: 'Dead',
//     species: 'Human',
//     type: '',
//     gender: 'Male',
//   },
//   {
//     id: 13,
//     name: 'Alien Googah',
//     status: 'unknown',
//     species: 'Alien',
//     type: '',
//     gender: 'unknown',
//   },
//   {
//     id: 14,
//     name: 'Alien Morty',
//     status: 'unknown',
//     species: 'Alien',
//     type: '',
//     gender: 'Male',
//   },
//   {
//     id: 15,
//     name: 'Alien Rick',
//     status: 'unknown',
//     species: 'Alien',
//     type: '',
//     gender: 'Male',
//   },
//   {
//     id: 16,
//     name: 'Amish Cyborg',
//     status: 'Dead',
//     species: 'Alien',
//     type: 'Parasite, Cyborg',
//     gender: 'Male',
//   },
//   {
//     id: 17,
//     name: 'Annie',
//     status: 'Alive',
//     species: 'Human',
//     type: '',
//     gender: 'Female',
//   },
//   {
//     id: 18,
//     name: 'Antenna Morty',
//     status: 'Alive',
//     species: 'Human',
//     type: 'Human with antennae',
//     gender: 'Male',
//   },
//   {
//     id: 19,
//     name: 'Antenna Rick',
//     status: 'unknown',
//     species: 'Human',
//     type: 'Human with antennae',
//     gender: 'Male',
//   },
//   {
//     id: 20,
//     name: 'Ants in my Eyes Johnson',
//     status: 'unknown',
//     species: 'Human',
//     type: 'Human with ants in his eyes',
//     gender: 'Male',
//   },
//   {
//     id: 21,
//     name: 'Aqua Morty',
//     status: 'unknown',
//     species: 'Humanoid',
//     type: 'Fish-Person',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/21.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/21',
//     created: '2017-11-04T22:39:48.055Z'
//   },
//   {
//     id: 22,
//     name: 'Aqua Rick',
//     status: 'unknown',
//     species: 'Humanoid',
//     type: 'Fish-Person',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/22.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/22',
//     created: '2017-11-04T22:41:07.171Z'
//   },
//   {
//     id: 23,
//     name: 'Arcade Alien',
//     status: 'unknown',
//     species: 'Alien',
//     type: '',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/23.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/23',
//     created: '2017-11-05T08:43:05.095Z'
//   },
//   {
//     id: 24,
//     name: 'Armagheadon',
//     status: 'Alive',
//     species: 'Alien',
//     type: 'Cromulon',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/24.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/24',
//     created: '2017-11-05T08:48:30.776Z'
//   },
//   {
//     id: 25,
//     name: 'Armothy',
//     status: 'Dead',
//     species: 'unknown',
//     type: 'Self-aware arm',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/25.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/25',
//     created: '2017-11-05T08:54:29.343Z'
//   },
//   {
//     id: 26,
//     name: 'Arthricia',
//     status: 'Alive',
//     species: 'Alien',
//     type: 'Cat-Person',
//     gender: 'Female',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/26.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/26',
//     created: '2017-11-05T08:56:46.165Z'
//   },
//   {
//     id: 27,
//     name: 'Artist Morty',
//     status: 'Alive',
//     species: 'Human',
//     type: '',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/27.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/27',
//     created: '2017-11-05T08:59:07.457Z'
//   },
//   {
//     id: 28,
//     name: 'Attila Starwar',
//     status: 'Alive',
//     species: 'Human',
//     type: '',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/28.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/28',
//     created: '2017-11-05T09:02:16.595Z'
//   },
//   {
//     id: 29,
//     name: 'Baby Legs',
//     status: 'Alive',
//     species: 'Human',
//     type: 'Human with baby legs',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/29.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/29',
//     created: '2017-11-05T09:06:19.644Z'
//   },
//   {
//     id: 30,
//     name: 'Baby Poopybutthole',
//     status: 'Alive',
//     species: 'Poopybutthole',
//     type: '',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/30.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/30',
//     created: '2017-11-05T09:13:16.483Z'
//   },
//   {
//     id: 31,
//     name: 'Baby Wizard',
//     status: 'Dead',
//     species: 'Alien',
//     type: 'Parasite',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/31.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/31',
//     created: '2017-11-05T09:15:11.286Z'
//   },
//   {
//     id: 32,
//     name: 'Bearded Lady',
//     status: 'Dead',
//     species: 'Alien',
//     type: 'Parasite',
//     gender: 'Female',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/32.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/32',
//     created: '2017-11-05T09:18:04.184Z'
//   },
//   {
//     id: 33,
//     name: 'Beebo',
//     status: 'Dead',
//     species: 'Alien',
//     type: '',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/33.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/33',
//     created: '2017-11-05T09:21:55.595Z'
//   },
//   {
//     id: 34,
//     name: 'Benjamin',
//     status: 'Alive',
//     species: 'Poopybutthole',
//     type: '',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/34.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/34',
//     created: '2017-11-05T09:24:04.748Z'
//   },
//   {
//     id: 35,
//     name: 'Bepisian',
//     status: 'Alive',
//     species: 'Alien',
//     type: 'Bepisian',
//     gender: 'unknown',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/35.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/35',
//     created: '2017-11-05T09:27:38.491Z'
//   },
//   {
//     id: 36,
//     name: 'Beta-Seven',
//     status: 'Alive',
//     species: 'Alien',
//     type: 'Hivemind',
//     gender: 'unknown',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/36.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/36',
//     created: '2017-11-05T09:31:08.952Z'
//   },
//   {
//     id: 37,
//     name: 'Beth Sanchez',
//     status: 'Alive',
//     species: 'Human',
//     type: '',
//     gender: 'Female',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/37.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/37',
//     created: '2017-11-05T09:38:22.960Z'
//   },
//   {
//     id: 38,
//     name: 'Beth Smith',
//     status: 'Alive',
//     species: 'Human',
//     type: '',
//     gender: 'Female',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/38.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/38',
//     created: '2017-11-05T09:48:44.230Z'
//   },
//   {
//     id: 39,
//     name: 'Beth Smith',
//     status: 'Alive',
//     species: 'Human',
//     type: '',
//     gender: 'Female',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/39.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/39',
//     created: '2017-11-05T09:52:31.777Z'
//   },
//   {
//     id: 40,
//     name: "Beth's Mytholog",
//     status: 'Dead',
//     species: 'Mytholog',
//     type: '',
//     gender: 'Female',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/40.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/40',
//     created: '2017-11-05T10:02:26.701Z'
//   },
//   {
//     id: 361,
//     name: 'Toxic Rick',
//     status: 'Dead',
//     species: 'Humanoid',
//     type: "Rick's toxic side",
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/361.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/361',
//     created: '2018-01-10T18:20:41.703Z'
//   },
//   {
//     id: 362,
//     name: 'Traflorkian',
//     status: 'Alive',
//     species: 'Alien',
//     type: 'Traflorkian',
//     gender: 'unknown',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/362.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/362',
//     created: '2018-01-10T18:52:08.927Z'
//   },
//   {
//     id: 363,
//     name: 'Trandor',
//     status: 'Alive',
//     species: 'Alien',
//     type: 'Krootabulan',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/363.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/363',
//     created: '2018-01-10T18:54:36.578Z'
//   },
//   {
//     id: 364,
//     name: 'Tree Person',
//     status: 'Dead',
//     species: 'Humanoid',
//     type: 'Teenyverse inhabitant',
//     gender: 'unknown',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/364.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/364',
//     created: '2018-01-10T18:57:50.033Z'
//   },
//   {
//     id: 365,
//     name: 'Tricia Lange',
//     status: 'Alive',
//     species: 'Human',
//     type: '',
//     gender: 'Female',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/365.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/365',
//     created: '2018-01-10T18:59:31.842Z'
//   },
//   {
//     id: 366,
//     name: 'Trunk Morty',
//     status: 'Alive',
//     species: 'Humanoid',
//     type: 'Trunk-Person',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/366.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/366',
//     created: '2018-01-10T19:03:13.558Z'
//   },
//   {
//     id: 367,
//     name: 'Trunk Man',
//     status: 'Alive',
//     species: 'Humanoid',
//     type: 'Trunk-Person',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/367.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/367',
//     created: '2018-01-10T19:05:34.004Z'
//   },
//   {
//     id: 368,
//     name: 'Truth Tortoise',
//     status: 'unknown',
//     species: 'Animal',
//     type: 'Omniscient being',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/368.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/368',
//     created: '2018-01-10T19:14:35.885Z'
//   },
//   {
//     id: 369,
//     name: 'Tusked Assassin',
//     status: 'unknown',
//     species: 'Alien',
//     type: 'Tuskfish',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/369.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/369',
//     created: '2018-01-10T19:17:00.093Z'
//   },
//   {
//     id: 370,
//     name: 'Two Guys with Handlebar Mustaches',
//     status: 'Alive',
//     species: 'Human',
//     type: '',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/370.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/370',
//     created: '2018-01-10T19:17:57.976Z'
//   },
//   {
//     id: 371,
//     name: 'Tumblorkian',
//     status: 'Alive',
//     species: 'Alien',
//     type: 'Tumblorkian',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/371.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/371',
//     created: '2018-01-10T19:18:44.560Z'
//   },
//   {
//     id: 372,
//     name: 'Unity',
//     status: 'Alive',
//     species: 'Alien',
//     type: 'Hivemind',
//     gender: 'Genderless',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/372.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/372',
//     created: '2018-01-10T19:20:50.211Z'
//   },
//   {
//     id: 373,
//     name: 'Unmuscular Michael',
//     status: 'Alive',
//     species: 'Human',
//     type: '',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/373.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/373',
//     created: '2018-01-10T19:22:04.075Z'
//   },
//   {
//     id: 374,
//     name: 'Vampire Master',
//     status: 'Alive',
//     species: 'Vampire',
//     type: '',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/374.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/374',
//     created: '2018-01-10T19:23:45.478Z'
//   },
//   {
//     id: 375,
//     name: 'Vance Maximus',
//     status: 'Dead',
//     species: 'Human',
//     type: '',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/375.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/375',
//     created: '2018-01-10T19:26:00.957Z'
//   },
//   {
//     id: 376,
//     name: 'Veronica Ann Bennet',
//     status: 'Alive',
//     species: 'Alien',
//     type: 'Gazorpian',
//     gender: 'Female',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/376.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/376',
//     created: '2018-01-10T19:27:06.246Z'
//   },
//   {
//     id: 377,
//     name: 'Voltematron',
//     status: 'Dead',
//     species: 'Alien',
//     type: 'Parasite',
//     gender: 'unknown',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/377.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/377',
//     created: '2018-01-10T19:29:08.116Z'
//   },
//   {
//     id: 378,
//     name: 'Wall Crawling Rick',
//     status: 'unknown',
//     species: 'Humanoid',
//     type: 'Lizard-Person',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/378.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/378',
//     created: '2018-01-10T19:33:30.804Z'
//   },
//   {
//     id: 379,
//     name: 'Wedding Bartender',
//     status: 'unknown',
//     species: 'Alien',
//     type: '',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/379.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/379',
//     created: '2018-01-10T19:37:41.375Z'
//   },
//   {
//     id: 380,
//     name: 'Weird Rick',
//     status: 'unknown',
//     species: 'Human',
//     type: '',
//     gender: 'Male',
//     origin: [Object],
//     location: [Object],
//     image: 'https://rickandmortyapi.com/api/character/avatar/380.jpeg',
//     episode: [Array],
//     url: 'https://rickandmortyapi.com/api/character/380',
//     created: '2018-01-10T19:44:22.262Z'
//   }
// ];


// localStorage.setItem("vCharsLocalStorage", chars);
// console.log(chars[0]);